create table user (id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), login varchar(255), password varchar(255), roleId bigint, primary key (id))

INSERT INTO User (id, email, firstName, lastName, login, password, roleId) VALUES (1, 'admin@gmail.com','Alex', 'Johns','admin', 'admin11', '1');
INSERT INTO User (id, email, firstName, lastName, login, password, roleId) VALUES (2, 'user@gmail.com','Alex', 'Johns','user', '111111', '2');

--INSERT INTO User (id, firstname, lastname, username, password, salary, age)  VALUES (2, 'Tom', 'Asr', 'tom234', '$2a$04$QED4arFwM1AtQWkR3JkQx.hXxeAk/G45NiRd3Q4ElgZdzGYCYKZOW', 7823, 23);
--INSERT INTO User (id, firstname, lastname, username, password, salary, age)  VALUES (3, 'Adam', 'Psr', 'adam', '$2a$04$WeT1SvJaGjmvQj34QG8VgO9qdXecKOYKEDZtCPeeIBSTxxEhazNla', 4234, 45);